
FROM golang:latest AS go-builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go get -d -v ./...

COPY assets assets
COPY cmd cmd
COPY pkg pkg

RUN ls -lha *

RUN go build -o main cmd/main.go

FROM ubuntu:latest

WORKDIR /app

COPY --from=go-builder /app/main /app/main
ENV MONGO_URI=mongodb://localhost:27017

EXPOSE 8082

CMD ["/app/main"]

